# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Humoroidui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Humoroid(object):
    def setupUi(self, Humoroid):
        Humoroid.setObjectName("Humoroid")
        Humoroid.resize(1240, 597)
        Humoroid.setAutoFillBackground(True)
        self.label = QtWidgets.QLabel(Humoroid)
        self.label.setGeometry(QtCore.QRect(-4, -10, 1311, 671))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:/images/blac.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Humoroid)
        self.label_2.setGeometry(QtCore.QRect(240, 60, 751, 401))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("E:/images/droid.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Humoroid)
        self.label_3.setGeometry(QtCore.QRect(-6, 0, 440, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("E:/images/BigheartedVagueFoal-small.gif"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Humoroid)
        self.label_4.setGeometry(QtCore.QRect(0, 80, 211, 191))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("E:/images/Ss2_load.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Humoroid)
        self.label_5.setGeometry(QtCore.QRect(-50, 280, 271, 151))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("E:/images/Radar-Concept.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Humoroid)
        self.label_6.setGeometry(QtCore.QRect(-80, 520, 411, 81))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("E:/images/FUI_LittleAnimations.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Humoroid)
        self.label_7.setGeometry(QtCore.QRect(950, 380, 351, 211))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("E:/images/neonglobe.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Humoroid)
        self.label_8.setGeometry(QtCore.QRect(1000, 190, 281, 181))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("E:/images/tumblr_nia6ssKzEb1qavoz6o1_640.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Humoroid)
        self.label_9.setGeometry(QtCore.QRect(970, 0, 301, 181))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("E:/images/GIF.webp"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.textBrowser = QtWidgets.QTextBrowser(Humoroid)
        self.textBrowser.setGeometry(QtCore.QRect(450, 10, 256, 51))
        font = QtGui.QFont()
        font.setFamily("Space Ranger")
        font.setPointSize(18)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background: transparent;\n"
"border-radius: none;"
"color: white;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Humoroid)
        self.textBrowser_2.setGeometry(QtCore.QRect(710, 10, 256, 51))
        font = QtGui.QFont()
        font.setFamily("Space Ranger")
        font.setPointSize(18)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background: transparent;\n"
"border-radius: none;"
"color: white;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton = QtWidgets.QPushButton(Humoroid)
        self.pushButton.setGeometry(QtCore.QRect(410, 530, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Space Ranger")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Humoroid)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 530, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Space Ranger")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Humoroid)
        QtCore.QMetaObject.connectSlotsByName(Humoroid)

    def retranslateUi(self, Humoroid):
        _translate = QtCore.QCoreApplication.translate
        Humoroid.setWindowTitle(_translate("Humoroid", "Dialog"))
        self.pushButton.setText(_translate("Humoroid", "start"))
        self.pushButton_2.setText(_translate("Humoroid", "Terminate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Humoroid = QtWidgets.QDialog()
    ui = Ui_Humoroid()
    ui.setupUi(Humoroid)
    Humoroid.show()
    sys.exit(app.exec_())
